# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataAnalysisGui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import MPLWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = MPLWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(210, 50, 811, 471))
        self.widget.setToolTipDuration(-4)
        self.widget.setObjectName("widget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 50, 131, 341))
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setObjectName("listWidget")
        self.clearPlotButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearPlotButton.setGeometry(QtCore.QRect(900, 10, 101, 31))
        self.clearPlotButton.setObjectName("clearPlotButton")
        self.multiplierLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.multiplierLineEdit.setEnabled(True)
        self.multiplierLineEdit.setGeometry(QtCore.QRect(250, 20, 51, 20))
        self.multiplierLineEdit.setClearButtonEnabled(False)
        self.multiplierLineEdit.setObjectName("multiplierLineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 0, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 0, 61, 16))
        self.label_2.setObjectName("label_2")
        self.offsetLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.offsetLineEdit.setGeometry(QtCore.QRect(320, 20, 51, 20))
        self.offsetLineEdit.setClearButtonEnabled(False)
        self.offsetLineEdit.setObjectName("offsetLineEdit")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(380, 20, 71, 21))
        self.resetButton.setObjectName("resetButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 430, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 500, 141, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 520, 141, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 450, 141, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 465, 131, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 480, 131, 16))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHep = QtWidgets.QMenu(self.menubar)
        self.menuHep.setObjectName("menuHep")
        self.menuFigure = QtWidgets.QMenu(self.menubar)
        self.menuFigure.setObjectName("menuFigure")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionComo_utilizar = QtWidgets.QAction(MainWindow)
        self.actionComo_utilizar.setObjectName("actionComo_utilizar")
        self.actionTitulo = QtWidgets.QAction(MainWindow)
        self.actionTitulo.setObjectName("actionTitulo")
        self.actionEixo_X = QtWidgets.QAction(MainWindow)
        self.actionEixo_X.setObjectName("actionEixo_X")
        self.actionEixo_Y = QtWidgets.QAction(MainWindow)
        self.actionEixo_Y.setObjectName("actionEixo_Y")
        self.menuFile.addAction(self.actionOpenFile)
        self.menuHep.addAction(self.actionComo_utilizar)
        self.menuFigure.addAction(self.actionTitulo)
        self.menuFigure.addAction(self.actionEixo_X)
        self.menuFigure.addAction(self.actionEixo_Y)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFigure.menuAction())
        self.menubar.addAction(self.menuHep.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Análise de Dados - Formula UFMG"))
        self.clearPlotButton.setText(_translate("MainWindow", "Limpar Figura"))
        self.multiplierLineEdit.setText(_translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "Multiplicador"))
        self.label_2.setText(_translate("MainWindow", "Offset"))
        self.offsetLineEdit.setText(_translate("MainWindow", "0"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.label_3.setText(_translate("MainWindow", "Pacotes recebidos: "))
        self.label_4.setText(_translate("MainWindow", "Número de pontos:"))
        self.label_5.setText(_translate("MainWindow", "Tempo decorrido:"))
        self.label_6.setText(_translate("MainWindow", "Pacote 1:"))
        self.label_7.setText(_translate("MainWindow", "Pacote 2:"))
        self.label_8.setText(_translate("MainWindow", "Pacote 3:"))
        self.menuFile.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuHep.setTitle(_translate("MainWindow", "Ajuda"))
        self.menuFigure.setTitle(_translate("MainWindow", "Figura"))
        self.actionOpenFile.setText(_translate("MainWindow", "Abrir"))
        self.actionComo_utilizar.setText(_translate("MainWindow", "Como utilizar"))
        self.actionTitulo.setText(_translate("MainWindow", "Titulo"))
        self.actionEixo_X.setText(_translate("MainWindow", "Eixo X"))
        self.actionEixo_Y.setText(_translate("MainWindow", "Eixo Y"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
