# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataAnalysisGui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import MPLWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 50, 131, 341))
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setObjectName("listWidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 430, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 500, 141, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 450, 141, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 465, 131, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 480, 131, 16))
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 231, 16))
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 231, 16))
        self.label_9.setObjectName("label_9")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(200, 0, 871, 621))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = MPLWidget(self.tab)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(20, 70, 841, 521))
        self.widget.setToolTipDuration(-4)
        self.widget.setObjectName("widget")
        self.resetButton = QtWidgets.QPushButton(self.tab)
        self.resetButton.setGeometry(QtCore.QRect(190, 40, 71, 21))
        self.resetButton.setObjectName("resetButton")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(60, 20, 61, 16))
        self.label.setObjectName("label")
        self.multiplierLineEdit = QtWidgets.QLineEdit(self.tab)
        self.multiplierLineEdit.setEnabled(True)
        self.multiplierLineEdit.setGeometry(QtCore.QRect(60, 40, 51, 20))
        self.multiplierLineEdit.setClearButtonEnabled(False)
        self.multiplierLineEdit.setObjectName("multiplierLineEdit")
        self.offsetLineEdit = QtWidgets.QLineEdit(self.tab)
        self.offsetLineEdit.setGeometry(QtCore.QRect(130, 40, 51, 20))
        self.offsetLineEdit.setClearButtonEnabled(False)
        self.offsetLineEdit.setObjectName("offsetLineEdit")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(140, 20, 61, 16))
        self.label_2.setObjectName("label_2")
        self.clearPlotButton = QtWidgets.QPushButton(self.tab)
        self.clearPlotButton.setGeometry(QtCore.QRect(670, 20, 101, 31))
        self.clearPlotButton.setObjectName("clearPlotButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFigure = QtWidgets.QMenu(self.menubar)
        self.menuFigure.setObjectName("menuFigure")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionComo_utilizar = QtWidgets.QAction(MainWindow)
        self.actionComo_utilizar.setObjectName("actionComo_utilizar")
        self.actionTitulo = QtWidgets.QAction(MainWindow)
        self.actionTitulo.setObjectName("actionTitulo")
        self.actionEixo_X = QtWidgets.QAction(MainWindow)
        self.actionEixo_X.setObjectName("actionEixo_X")
        self.actionEixo_Y = QtWidgets.QAction(MainWindow)
        self.actionEixo_Y.setObjectName("actionEixo_Y")
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFigure.addAction(self.actionTitulo)
        self.menuFigure.addAction(self.actionEixo_X)
        self.menuFigure.addAction(self.actionEixo_Y)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFigure.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Análise de Dados - Formula UFMG"))
        self.label_3.setText(_translate("MainWindow", "Pacotes recebidos: "))
        self.label_4.setText(_translate("MainWindow", "Número de pontos:"))
        self.label_6.setText(_translate("MainWindow", "Pacote 1:"))
        self.label_7.setText(_translate("MainWindow", "Pacote 2:"))
        self.label_8.setText(_translate("MainWindow", "Pacote 3:"))
        self.label_5.setText(_translate("MainWindow", "Clique duas vezes para plotar"))
        self.label_9.setText(_translate("MainWindow", "uas vezes novamente para remover"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.label.setText(_translate("MainWindow", "Multiplicador"))
        self.multiplierLineEdit.setText(_translate("MainWindow", "1"))
        self.offsetLineEdit.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Offset"))
        self.clearPlotButton.setText(_translate("MainWindow", "Limpar Figura"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuFigure.setTitle(_translate("MainWindow", "Figura"))
        self.actionOpenFile.setText(_translate("MainWindow", "Abrir"))
        self.actionComo_utilizar.setText(_translate("MainWindow", "Como utilizar"))
        self.actionTitulo.setText(_translate("MainWindow", "Titulo"))
        self.actionEixo_X.setText(_translate("MainWindow", "Eixo X"))
        self.actionEixo_Y.setText(_translate("MainWindow", "Eixo Y"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
